### PR TITLE
feat: add metric for returning users

### PR DESCRIPTION
**Pull request by xcoulon**
when reactivating a user, make sure that the
`toolchain.dev.openshift.com/activation-counter`
annotation is preserved on the corresponding
`UserSignup` resource.

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]
Do not forget to update the PR to point to master api before merging :)

**Comment by xcoulon** [comment]
> Do not forget to update the PR to point to master api before merging :)

Thanks for the reminder! Actually, since I'm using a constant defined in https://github.com/codeready-toolchain/api/pull/224, I will also split that PR

**Comment by xcoulon** [comment]
> > Do not forget to update the PR to point to master api before merging :)
> 
> Thanks for the reminder! Actually, since I'm using a constant defined in [codeready-toolchain/api#224](https://github.com/codeready-toolchain/api/pull/224), I will also split that PR

See https://github.com/codeready-toolchain/api/pull/227

**Pull request merged**
