### PR TITLE
Update toolchain-common

### PR DESCRIPTION
**Pull request by filariow**
Signed-off-by: Francesco Ilario <filario@redhat.com>

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]
:rocket: :+1:

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
It looks like we have a broken unit tests now (not related to your PR). We need to look at this ASAP. It currently blocks all reg-service PRs.
cc: @ranakan19

**Comment by alexeykazakov** [comment]
FYI. There is was an attempt from Matous to fix it: https://github.com/codeready-toolchain/registration-service/pull/374 Which doesn't work. We need to keep investigating.

**Comment by filariow** [comment]
@alexeykazakov thanks for letting me know, I've proposed an attempt in #375

**Pull request merged**
