### PR TITLE
Updating the UUID dependency to use googleUUID

### PR DESCRIPTION
**Pull request by fbm3307**
This is updating the UUID pkg from gofrs to Google

Since in Toolchain - Common  [PR](https://github.com/codeready-toolchain/toolchain-common/pull/395) it is already updated , Updating them in its related repos

- Toolchain- e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/968

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
Looks good 👍 

Thanks for updating this.

**Review by metlos — APPROVED** [review]
👍🏼

**Review by MatousJobanek — APPROVED** [review]
Thanks
/lgtm

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
