### PR TITLE
Disable TLS verify for sso key fetching if not in prod

### PR DESCRIPTION
**Pull request by alexeykazakov**
This is for working around the cert verification issue when running Sandbox in test environment and using a test keycloak instance over https.
The AppStudio QE team faced this issue.

### CODE REVIEW

**Review by rajivnathan — APPROVED** [review]

**Review by MatousJobanek — APPROVED** [review]

**Comment by alexeykazakov** [comment]
/retest

infra issue

**Comment by alexeykazakov** [comment]
/retest

infra again

**Comment by alexeykazakov** [comment]
/retest

infra

**Comment by alexeykazakov** [comment]
/retest

infra

**Comment by alexeykazakov** [comment]
/retest

infra

**Pull request merged**
