### PR TITLE
chore: add get/list bannedusers to reg-service SA

### PR DESCRIPTION
**Pull request by MatousJobanek**
https://github.com/codeready-toolchain/host-operator/pull/151

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Seems to be a problem with reg-service image again?
```
Error from server (BadRequest): container "registration-service" in pod "registration-service-7c97f64b6d-4l6nk" is waiting to start: trying and failing to pull image
```

**Comment by MatousJobanek** [comment]
> Seems to be a problem with reg-service image again?

not really. To be honest, I have no idea what is going on. It looks like the e2e tests are executed in a different namespace than the image was built.  

From the images build:
```
 2020/03/03 15:23:45 Using namespace ci-op-ijstr0r3
2020/03/03 15:23:45 Running root, [input:os], [release-inputs], src, bin, registration-service, [output:stable:registration-service], [images]
2020/03/03 15:23:45 Creating namespace ci-op-ijstr0r3
2020/03/03 15:23:45 Creating rolebinding for user MatousJobanek in namespace ci-op-ijstr0r3
2020/03/03 15:23:45 Setting up pipeline imagestream for the test
2020/03/03 15:23:45 Building root
2020/03/03 15:23:45 Tagging https://api.ci.openshift.org/openshift/centos:7 into pipeline:os
2020/03/03 15:23:45 Tagged shared images from ocp/4.3:${component}, images will be pullable from default-route-openshift-image-registry.apps.build01.ci.devcluster.openshift.com/ci-op-ijstr0r3/stable:${component} 
```
but in the e2e build, there is:
```
 2020/03/04 09:38:35 Using namespace ci-op-9pfg6jzm
2020/03/04 09:38:35 Running root, [input:os], [release-inputs], src, bin, registration-service, [output:stable:registration-service], [images], [release:latest], e2e
2020/03/04 09:38:35 Creating namespace ci-op-9pfg6jzm 
```
so the logic counts the image location as: 
```
registry.svc.ci.openshift.org/ci-op-9pfg6jzm/stable:registration-service
```
which is wrong :man_shrugging:

**Pull request merged**
