### PR TITLE
fix: ldflags build time in github

### PR DESCRIPTION
**Pull request by mfrancisc**
Small fix for build time still not being populated in prod.

Jira story: https://issues.redhat.com/browse/SANDBOX-53

### CODE REVIEW

**Review by xcoulon — APPROVED** [review]
good catch!

**Comment by mfrancisc** [comment]
/retest

potential flaky test: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/codeready-toolchain_registration-service/325/pull-ci-codeready-toolchain-registration-service-master-e2e/1661767219438161920/build-log.txt

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
