### PR TITLE
woopra and segment endpoints

### PR DESCRIPTION
**Pull request by tinakurian**
Jira: https://issues.redhat.com/browse/CRT-853
Related PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/205, https://github.com/codeready-toolchain/host-operator/pull/334
This PR creates two new endpoints; one for retrieving the woopra domain and another for retrieving the segment-write-key.

Renaming of branch to pair with e2e tests: https://github.com/codeready-toolchain/toolchain-e2e/pull/205

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]
I assume there it's just a duplication of the closed PR which was already approved.
Please let me know if you have changed anything.

**Comment by tinakurian** [comment]
> I assume there it's just a duplication of the closed PR which was already approved.
> Please let me know if you have changed anything.

Yes, that's right, didn't change anything.

**Pull request merged**
