### PR TITLE
Use OpenShift template to deploy reg-service

### PR DESCRIPTION
**Pull request by alexeykazakov**
- One template for both e2e test and dev env.
- ConfigMap with params to configure deployments in specific env
- Liveness and Readness probs
- No Node ports anymore. So there can be multiple reg-services deployments (useful for dev and test envs)
- Replace TestingMode env var by Environment (prod, stage, dev, unit-tests, e2e-tests, etc)

Paired e2e test PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/37

### CODE REVIEW

**Comment by nurali-techie** [comment]
@alexeykazakov `deployment_dev.yaml` which is getting deleted in this PR is used here  https://github.com/codeready-toolchain/toolchain-e2e/blob/master/make/test.mk#L260

**Comment by alexeykazakov** [comment]
> deployment_dev.yaml which is getting deleted in this PR is used here https://github.com/codeready-toolchain/toolchain-e2e/blob/master/make/test.mk#L260

@nurali-techie yeah I know.
See https://github.com/codeready-toolchain/toolchain-e2e/pull/37

**Comment by tinakurian** [comment]
looks like the e2e tests failed..

```
verifying github.com/operator-framework/operator-sdk@v0.11.0: checksum mismatch
	downloaded: h1:If0MefBJjPGYAW6Os6azpTMoaFtsSlXRlQctF23/ORs=
	go.sum:     h1:tQumPT2UjD6uhggfAerRbPt+rWOPKC80DmgKUEqeGYo=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by alexeykazakov** [comment]
> looks like the e2e tests failed..

Yeah.. We need to switch to golang 1.13 in Dockertools - https://github.com/codeready-toolchain/registration-service/pull/65

**Pull request merged**
