### PR TITLE
fix: use UTC time in tests

### PR DESCRIPTION
**Pull request by filariow**

### CODE REVIEW

**Review by rajivnathan — COMMENTED** [review]
Was there something that prompted this change?

**Comment by filariow** [comment]
> Was there something that prompted this change?

I was not able to understand the reason why, but these tests started failing on my local with both `go 1.20.8` and `1.22.2`.

**Comment by rajivnathan** [comment]
>I was not able to understand the reason why, but these tests started failing on my local with both go 1.20.8 and 1.22.2.

That's interesting, I just tried without your changes and it's failing for me too. I verified your change resolves it but it would be good to understand why. It looks like it could be related to https://github.com/codeready-toolchain/registration-service/pull/432 cc @sbryzak

**Comment by filariow** [comment]
I think the main reason why we didn't notice this before merging #432 is that the CI instances are running with timezone set to UTC.

**Review by rajivnathan — APPROVED** [review]
Ok looks like this was probably just missed from the original PR. I think the fix is good 👍

**Pull request merged**
