### PR TITLE
Remove michael's name from reviewers

### PR DESCRIPTION
**Pull request by fbm3307**

### CODE REVIEW

**Review by rajivnathan — APPROVED** [review]

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
/retest

Another flaky test?
```
--- FAIL: TestE2EFlow (551.48s)
    --- PASS: TestE2EFlow/users_pods_webhook (0.00s)
    --- PASS: TestE2EFlow/virtual_machine_webhook (0.00s)
    --- PASS: TestE2EFlow/verify_cluster_statuses_are_valid (0.25s)
        --- PASS: TestE2EFlow/verify_cluster_statuses_are_valid/verify_member_cluster_status (0.12s)
        --- PASS: TestE2EFlow/verify_cluster_statuses_are_valid/verify_overall_toolchain_status (0.13s)
    --- PASS: TestE2EFlow/verify_MemberOperatorConfigs_synced_from_ToolchainConfig_to_member_clusters (0.36s)
        --- PASS: TestE2EFlow/verify_MemberOperatorConfigs_synced_from_ToolchainConfig_to_member_clusters/verify_ToolchainConfig_has_synced_status (0.11s)
        --- PASS: TestE2EFlow/verify_MemberOperatorConfigs_synced_from_ToolchainConfig_to_member_clusters/verify_MemberOperatorConfig_was_synced_to_member_1 (0.11s)
        --- PASS: TestE2EFlow/verify_MemberOperatorConfigs_synced_from_ToolchainConfig_to_member_clusters/verify_MemberOperatorConfig_was_synced_to_member_2 (0.12s)
    --- FAIL: TestE2EFlow/try_to_break_UserAccount (151.31s)
        --- PASS: TestE2EFlow/try_to_break_UserAccount/delete_user_and_wait_until_recreated (19.95s)
        --- FAIL: TestE2EFlow/try_to_break_UserAccount/delete_identity_and_wait_until_recreated (131.36s)
```

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_registration-service/431/pull-ci-codeready-toolchain-registration-service-master-e2e/1790686297266851840

**Comment by alexeykazakov** [comment]
/retest

And the spacerequest flaky test again?
```
=== NAME  TestSpaceLister
    clean.go:184: the related MasterUserRecord: bus is deleted as well
    clean.go:184: the related MasterUserRecord: bus is deleted as well
    clean.go:161: 
        	Error Trace:	/tmp/toolchain-e2e/testsupport/cleanup/clean.go:161
        	            				/usr/local/go/src/sync/once.go:74
        	            				/usr/local/go/src/sync/once.go:65
        	            				/tmp/toolchain-e2e/testsupport/cleanup/clean.go:92
        	            				/tmp/toolchain-e2e/testsupport/cleanup/clean.go:76
        	            				/usr/local/go/src/runtime/asm_amd64.s:1598
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestSpaceLister
        	Messages:   	The object still exists after the time out expired: (*v1alpha1.SpaceBindingRequest)(0xc00074bb80)({
        	            	 TypeMeta: (v1.TypeMeta) &TypeMeta{Kind:,APIVersion:,},
        	            	 ObjectMeta: (v1.ObjectMeta) &ObjectMeta{Name:testspacelister-7wlwb,GenerateName:testspacelister-,Namespace:bus-tenant,SelfLink:,UID:bf165864-8a8a-4967-a17b-4bcf29f1fbe9,ResourceVersion:78083,Generation:2,CreationTimestamp:2024-05-15 19:46:11 +0000 UTC,DeletionTimestamp:2024-05-15 19:47:41 +0000 UTC,DeletionGracePeriodSeconds:*0,Labels:map[string]string{},Annotations:map[string]string{},OwnerReferences:[]OwnerReference{},Finalizers:[finalizer.toolchain.dev.openshift.com],ManagedFields:[]ManagedFieldsEntry{ManagedFieldsEntry{Manager:host-operator,Operation:Update,APIVersion:toolchain.dev.openshift.com/v1alpha1,Time:2024-05-15 19:46:11 +0000 UTC,FieldsType:FieldsV1,FieldsV1:{"f:metadata":{"f:finalizers":{".":{},"v:\"finalizer.toolchain.dev.openshift.com\"":{}}}},Subresource:,},ManagedFieldsEntry{Manager:host-operator,Operation:Update,APIVersion:toolchain.dev.openshift.com/v1alpha1,Time:2024-05-15 19:46:11 +0000 UTC,FieldsType:FieldsV1,FieldsV1:{"f:status":{".":{},"f:conditions":{".":{},"k:{\"type\":\"Ready\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}},Subresource:status,},ManagedFieldsEntry{Manager:parallel.test,Operation:Update,APIVersion:toolchain.dev.openshift.com/v1alpha1,Time:2024-05-15 19:46:11 +0000 UTC,FieldsType:FieldsV1,FieldsV1:{"f:metadata":{"f:generateName":{}},"f:spec":{".":{},"f:masterUserRecord":{},"f:spaceRole":{}}},Subresource:,},},},
        	            	 Spec: (v1alpha1.SpaceBindingRequestSpec) {
        	            	  MasterUserRecord: (string) (len=3) "car",
        	            	  SpaceRole: (string) (len=11) "invalidRole"
        	            	 },
        	            	 Status: (v1alpha1.SpaceBindingRequestStatus) {
        	            	  Conditions: ([]v1alpha1.Condition) (len=1 cap=4) {
        	            	   (v1alpha1.Condition) {
        	            	    Type: (v1alpha1.ConditionType) (len=5) "Ready",
        	            	    Status: (v1.ConditionStatus) (len=5) "False",
        	            	    LastTransitionTime: (v1.Time) 2024-05-15 19:46:11 +0000 UTC,
        	            	    Reason: (string) (len=26) "UnableToCreateSpaceBinding",
        	            	    Message: (string) (len=42) "invalid role 'invalidRole' for space 'bus'",
        	            	    LastUpdatedTime: (*v1.Time)(<nil>)
        	            	   }
        	            	  }
        	            	 }
        	            	})
=== NAME  TestUpdateNSTemplateTier
    member.go:726: waiting for NSTemplateSet 'cheesecakeuser08' to match criteria
=== NAME  TestSpaceLister
    clean.go:159: 
        	Error Trace:	/tmp/toolchain-e2e/testsupport/cleanup/clean.go:159
        	            				/usr/local/go/src/sync/once.go:74
        	            				/usr/local/go/src/sync/once.go:65
        	            				/tmp/toolchain-e2e/testsupport/cleanup/clean.go:92
        	            				/tmp/toolchain-e2e/testsupport/cleanup/clean.go:76
        	            				/usr/local/go/src/runtime/asm_amd64.s:1598
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestSpaceLister
        	Messages:   	The proper cleanup of the UserSignup 'bus' and related resources wasn't finished within the given timeout
        	            	the UserSignup 'bus' has been cleaned properly 
        	            	the MasterUserRecord 'bus' has been cleaned properly 
        	            	the Space 'bus' is still present in the cluster: &{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:bus GenerateName: Namespace:toolchain-host-15193058 SelfLink: UID:c8c99ff7-94ee-48e5-aac9-dd95db66f6dd ResourceVersion:78137 Generation:3 CreationTimestamp:2024-05-15 19:41:58 +0000 UTC DeletionTimestamp:2024-05-15 19:47:41 +0000 UTC DeletionGracePeriodSeconds:0xc000acd028 Labels:map[toolchain.dev.openshift.com/appstudio-tier-hash:5f6f7df30efeed061963a9ed0955dd42 toolchain.dev.openshift.com/creator:bus toolchain.dev.openshift.com/state:cluster-assigned] Annotations:map[] OwnerReferences:[] Finalizers:[finalizer.toolchain.dev.openshift.com] ManagedFields:[{Manager:parallel.test Operation:Update APIVersion:toolchain.dev.openshift.com/v1alpha1 Time:2024-05-15 19:42:26 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:spec":{"f:tierName":{}}} Subresource:} {Manager:host-operator Operation:Update APIVersion:toolchain.dev.openshift.com/v1alpha1 Time:2024-05-15 19:42:40 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:metadata":{"f:finalizers":{".":{},"v:\"finalizer.toolchain.dev.openshift.com\"":{}},"f:labels":{".":{},"f:toolchain.dev.openshift.com/appstudio-tier-hash":{},"f:toolchain.dev.openshift.com/creator":{},"f:toolchain.dev.openshift.com/state":{}}},"f:spec":{".":{},"f:targetCluster":{},"f:targetClusterRoles":{}}} Subresource:} {Manager:host-operator Operation:Update APIVersion:toolchain.dev.openshift.com/v1alpha1 Time:2024-05-15 19:47:41 +0000 UTC FieldsType:FieldsV1 FieldsV1:{"f:status":{".":{},"f:conditions":{".":{},"k:{\"type\":\"Ready\"}":{".":{},"f:lastTransitionTime":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:provisionedNamespaces":{},"f:targetCluster":{}}} Subresource:status}]} Spec:{TargetCluster:member-ci-op-qbmkg1rz-93ede.devsandboxci.devcluster.openshift2 TargetClusterRoles:[cluster-role.toolchain.dev.openshift.com/tenant] TierName:appstudio ParentSpace: DisableInheritance:false} Status:{TargetCluster:member-ci-op-qbmkg1rz-93ede.devsandboxci.devcluster.openshift2 ProvisionedNamespaces:[{Name:bus-tenant Type:default}] Conditions:[{Type:Ready Status:False LastTransitionTime:2024-05-15 19:47:41 +0000 UTC Reason:Terminating Message: LastUpdatedTime:<nil>}]}} 
--- FAIL: TestSpaceLister (481.77s)
```
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_registration-service/431/pull-ci-codeready-toolchain-registration-service-master-e2e/1790816340630573056

**Pull request merged**
